### ISSUE TITLE
Images in documentation are broken

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-privacy#64]
ref https://github.com/humanmade/marketing-sites/issues/1635

**Docs pages to be updated by Product team (@rmccue):**
- [ ] https://docs.altis-dxp.com/nightly/privacy/privacy-api/ | https://docs.altis-dxp.com/privacy/privacy-api/assets/data-export.png
- [ ] https://docs.altis-dxp.com/nightly/privacy/privacy-api/ | https://docs.altis-dxp.com/privacy/privacy-api/assets/privacy-page-settings.png
- [ ] https://docs.altis-dxp.com/privacy/privacy-api/ | https://docs.altis-dxp.com/privacy/privacy-api/assets/privacy-page-settings.png
- [ ] https://docs.altis-dxp.com/privacy/privacy-api/ | https://docs.altis-dxp.com/privacy/privacy-api/assets/data-export.png
- [ ] https://docs.altis-dxp.com/v6/privacy/privacy-api/ | https://docs.altis-dxp.com/v6/privacy/privacy-api/assets/data-export.png
- [ ] https://docs.altis-dxp.com/v6/privacy/privacy-api/ | https://docs.altis-dxp.com/v6/privacy/privacy-api/assets/privacy-page-settings.png
- [ ] https://docs.altis-dxp.com/v7/privacy/privacy-api/ | https://docs.altis-dxp.com/v7/privacy/privacy-api/assets/data-export.png
- [ ] https://docs.altis-dxp.com/v7/privacy/privacy-api/ | https://docs.altis-dxp.com/v7/privacy/privacy-api/assets/privacy-page-settings.png
- [ ] https://docs.altis-dxp.com/v8/privacy/privacy-api/ | https://docs.altis-dxp.com/v8/privacy/privacy-api/assets/privacy-page-settings.png
- [ ] https://docs.altis-dxp.com/v8/privacy/privacy-api/ | https://docs.altis-dxp.com/v8/privacy/privacy-api/assets/data-export.png

**Comment by robindevitt** [comment]
Do we have the appropriate images saved anywhere in particular that can be used or were in place?

**Comment by roborourke** [comment]
@robindevitt guess they've been missing the whole time! The images are the wiki for the consent plugin, I guess that's how they got missed initially when the docs were ported over, click the pages here to find and save all the images: https://github.com/humanmade/altis-consent/wiki/Privacy-Settings-page

**Comment by roborourke** [comment]
Actually thinking this might be a good first issue for @mikelittle as part of your onboarding checklist as it's straightforward and low risk.

Essentially need to copy the images from the Consent Plugin's wiki and put them in the `docs/assets` folder in this repo and check that the images show when you preview the markdown locally.

**Comment by roborourke** [comment]
Fixed in #69

**Comment by mikelittle** [comment]
I had to add a new image as the 'data-export' image does not appear in the privacy wiki. 
I also updated the image from the wiki as the screenshot was out of date.
