### ISSUE TITLE
Update Consent API to include latest Consent JS API changes

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-privacy#8]
The current version of Altis Consent requires a version of the Consent JS API that has a bug. While a `composer update` will fix this, it would be better to require a version that we know does not have issues.

**Comment by jazzsequence** [comment]
fixed via #9

**Comment by roborourke** [comment]
Not sure why this was reopened, maybe while the backport was in progress still. Seems to be done and backported now.
